version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mainDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      -  ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      guynet:
        ipv4_address: 10.5.0.5

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      guynet:
        ipv4_address: 10.5.0.6
    
networks:
  guynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
  
    